<?php

/**
 * @file
 * Implements different hook().
 */

use Drupal\Core\Form\FormStateInterface;

// Use Drupal\Core\Entity\EntityInterface;.

/**
 * @file
 * Contains preethy_exercise.module.
 */

/**
 * Implements hook_form_alter().
 */
function preethy_exercise_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // $route = \Drupal::routeMatch()->getRouteName();
  // print_r($route);
  // exit;
  $data = \Drupal::service('custom_service')->getName();
  // print_r($data);
  // exit;
}

/**
 * Implements hook_theme().
 */
function preethy_exercise_theme($existing, $type, $theme, $path) {

  return [
    'block_plugin_template' => [
      'variables' => [
        'text' => "",
        'hexcode' => "",
      ],
    ],
  ];

}

/**
 * Implements hook_user_login().
 */
function preethy_exercise_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

/**
 * Implements hook_page_attachments_alter().
 */
function preethy_exercise_page_attachments_alter(array &$attachments) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  // Check if the current route is admin.content.comment.
  if ($route_name === 'comment.admin') {
    // Modify or add attachments as needed.
    $attachments['#attached']['library'][] = 'preethy_exercise/css_lib';

  }
  // For view node.
  elseif ($route_name == 'entity.node.canonical') {
    $attachments['#attached']['library'][] = 'preethy_exercise/css_lib';

  }
}
